# <ruby>誤り<rt>エラー</rt></ruby>処理

信頼性へのRustの取り組みは、<ruby>誤り<rt>エラー</rt></ruby>処理にまで及んでいます。
<ruby>譜体<rt>アプリケーション</rt></ruby>では<ruby>誤り<rt>エラー</rt></ruby>は人生の事実なので、Rustには何かがうまくいかない状況を処理するための多くの機能があります。
多くの場合、Rustは<ruby>誤り<rt>エラー</rt></ruby>の可能性を認識し、<ruby>譜面<rt>コード</rt></ruby>が<ruby>製譜<rt>コンパイル</rt></ruby>される前に何らかの動作をとる必要があります。
この要件は、<ruby>譜面<rt>コード</rt></ruby>を本番環境に導入する前に、<ruby>誤り<rt>エラー</rt></ruby>を発見して適切に処理することによって、<ruby>算譜<rt>プログラム</rt></ruby>をより堅牢にします。

Rustは、<ruby>誤り<rt>エラー</rt></ruby>を*回復可能* *な*<ruby>誤り<rt>エラー</rt></ruby>と*回復不可能な*<ruby>誤り<rt>エラー</rt></ruby>の2つの主要な分類に分類します。
ファイルが見つからないなどの回復可能な<ruby>誤り<rt>エラー</rt></ruby>の場合、問題を利用者に報告して操作を再試行するのが妥当です。
回復不可能な<ruby>誤り<rt>エラー</rt></ruby>は、配列の終わりを超えた場所にアクセスしようとするような、常にバグの症状です。

ほとんどの言語は、例外などのしくみを使用して、これらの2種類の<ruby>誤り<rt>エラー</rt></ruby>を区別せず、同じ方法で両方を処理しません。
Rustには例外がありません。
その代わりに、回復可能な<ruby>誤り<rt>エラー</rt></ruby>の場合は`Result<T, E>`、回復不可能な<ruby>誤り<rt>エラー</rt></ruby>が発生した場合は実行を停止する`panic!`マクロがあります。
この章ではまず`panic!`を呼び出す方法について説明し、次に`Result<T, E>`値を返す方法について説明します。
さらに、<ruby>誤り<rt>エラー</rt></ruby>からの回復を試みるか、実行を停止するかを決定する際に考慮すべき点について検討します。
